# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(unique=True)),
                ('area_name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_areas',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField(unique=True)),
                ('building_number', models.CharField(max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_buildings',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(unique=True)),
                ('candidate_name', models.CharField(max_length=250)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_candidates',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_id', models.IntegerField(unique=True)),
                ('education_name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_education',
            },
        ),
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_status_id', models.IntegerField(unique=True)),
                ('family_status_name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_family_status',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(unique=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('middlename', models.CharField(max_length=255, null=True)),
                ('datebirth', models.DateField(null=True)),
                ('cellphone', models.CharField(max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_family_status',
            },
        ),
        migrations.CreateModel(
            name='FollowerCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(unique=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_follower_candidates',
            },
        ),
        migrations.CreateModel(
            name='FollowerContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('contact_date', models.DateField(null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_follower_contacts',
            },
        ),
        migrations.CreateModel(
            name='FollowerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_status_id', models.IntegerField(unique=True)),
                ('follower_status_name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_follower_status',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_id', models.IntegerField(unique=True)),
                ('locality_name', models.CharField(max_length=56)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_localities',
            },
        ),
        migrations.CreateModel(
            name='PollPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polplace_id', models.IntegerField(unique=True)),
                ('polplace_number', models.CharField(max_length=14, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_polplaces',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('project_name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(unique=True)),
                ('area_name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_project_contacts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(unique=True)),
                ('region_name', models.CharField(max_length=250)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_regions',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_id', models.IntegerField(unique=True)),
                ('sex_name', models.CharField(max_length=225)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_sex',
            },
        ),
        migrations.CreateModel(
            name='SocialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_category_id', models.IntegerField(unique=True)),
                ('social_category_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_social_category',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_id', models.IntegerField(unique=True)),
                ('street_name', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_route': 'external_app',
                'db_table': 'sms_view_streets',
            },
        ),
        migrations.CreateModel(
            name='Alphaname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'BLOCKED'), (2, 'MODERATE'), (3, 'LIMITED')])),
                ('registration_date', models.DateField()),
                ('created_by_crm_user_id', models.IntegerField()),
            ],
            options={
                'db_route': 'internal_app',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('datetime_sent', models.DateTimeField()),
                ('state', models.TextField()),
            ],
            options={
                'db_route': 'internal_app',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('message_text', models.CharField(max_length=402)),
                ('datetime_scheduled', models.DateTimeField()),
                ('datetime_sent', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'SENT'), (2, 'DELIVERED'), (3, 'EXPIRED'), (4, 'UNDELIV'), (5, 'STOPED'), (6, 'ERROR'), (7, 'USERSTOPED'), (8, 'ALFANAMELIMITED'), (9, 'STOPFLAG'), (10, 'NEW')])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSApp.Campaign')),
                ('crm_elector_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SMSApp.Follower', to_field='follower_id')),
            ],
            options={
                'db_route': 'internal_app',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message_text', models.CharField(max_length=402)),
                ('code', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'one-time'), (1, 'recurring'), (2, 'event-driven')])),
                ('end_date', models.DateField()),
                ('created_by_crm_user_id', models.IntegerField()),
                ('triggered_by', models.IntegerField(choices=[(0, 'onElectorBirthday'), (1, 'onElectorAdded'), (2, 'onElectorTouched'), (3, 'onElectorStatusChanged')], null=True)),
                ('target_filter', models.TextField()),
                ('state', models.IntegerField(choices=[(0, 'active'), (1, 'paused'), (2, 'complete')])),
                ('alphaname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSApp.Alphaname')),
            ],
            options={
                'db_route': 'internal_app',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSApp.Task'),
        ),
    ]
