# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='alphaname',
            name='status',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'BLOCKED'), (2, 'MODERATE'), (3, 'LIMITED')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
