# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='touch_candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SMSApp.Candidate'),
        ),
        migrations.AddField(
            model_name='task',
            name='touch_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SMSApp.ProjectContact'),
        ),
        migrations.AddField(
            model_name='task',
            name='touch_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SMSApp.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='touch_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='SMSApp.FollowerStatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='trigger_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='SMSApp.FollowerStatus'),
        ),
    ]
