# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0002_auto_20160602_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='smsfly_campaign_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
