# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0003_campaign_smsfly_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='triggered_by',
            field=models.CharField(choices=[('onElectorBirthday', 'День рождения избирателя'), ('onElectorAdded', 'Внесение анкеты избирателя в базу'), ('onElectorTouched', 'Внесение касания с избирателем в базу'), ('onElectorStatusChanged', 'Смена статуса избирателя')], max_length=22, null=True),
        ),
    ]
