# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0004_auto_20160611_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'get_latest_by': 'datetime_sent'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='SMSApp.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_rule',
            field=recurrence.fields.RecurrenceField(),
        ),
        migrations.AlterModelTable(
            name='follower',
            table='sms_view_followers',
        ),
    ]
