# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0006_auto_20160627_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cost',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='smsfly_campaign_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='triggered_by',
            field=models.CharField(choices=[('onElectorBirthday', "On elector's birthday"), ('onElectorAdded', 'On adding elector to the database'), ('onElectorTouched', 'Elector touched'), ('onElectorStatusChanged', 'On elector status change')], max_length=22, null=True),
        ),
    ]
